[package]
name = "checklist"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "backend/basic/todoapp"
, "backend/basic/urlshortener"]

[dependencies]
todoapp = { path = "backend/basic/todoapp" }
urlshortener = { path = "backend/basic/urlshortener" }
